/*
 * V_cancleanddo.java
 *
 * Created on __DATE__, __TIME__
 */

package com.CCL.view.huiyuan.son;

import com.CCL.beans.Customer;
import com.CCL.beans.CustomerState;
import com.CCL.view.huiyuan.VipManager;
import com.CCL.view.huiyuan.service.CustomerService;

import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JTextField;

/**
 *
 * @author  __USER__
 */
public class V_cancleanddo extends javax.swing.JPanel {


	/** Creates new form V_cancleanddo */
	public V_cancleanddo() {
		
		initComponents();
	}

	public javax.swing.JList getjList1() {
		return jList1;
	}

	public void setjList1(javax.swing.JList jList1) {
		this.jList1 = jList1;
	}

	public javax.swing.JScrollPane getjScrollPane1() {
		return jScrollPane1;
	}

	public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
		this.jScrollPane1 = jScrollPane1;
	}

	public javax.swing.JSeparator getjSeparator1() {
		return jSeparator1;
	}

	public void setjSeparator1(javax.swing.JSeparator jSeparator1) {
		this.jSeparator1 = jSeparator1;
	}

	public javax.swing.JButton getJbt_cancle1() {
		return jbt_cancle1;
	}

	public void setJbt_cancle1(javax.swing.JButton jbt_cancle1) {
		this.jbt_cancle1 = jbt_cancle1;
	}

	public javax.swing.JButton getJbt_cancle2() {
		return jbt_cancle2;
	}

	public void setJbt_cancle2(javax.swing.JButton jbt_cancle2) {
		this.jbt_cancle2 = jbt_cancle2;
	}

	public javax.swing.JButton getJbt_ok() {
		return jbt_ok;
	}

	public void setJbt_ok(javax.swing.JButton jbt_ok) {
		this.jbt_ok = jbt_ok;
	}

	public javax.swing.JButton getJbt_save() {
		return jbt_save;
	}

	public void setJbt_save(javax.swing.JButton jbt_save) {
		this.jbt_save = jbt_save;
	}

	public javax.swing.JLabel getLbl_cancle() {
		return lbl_cancle;
	}

	public void setLbl_cancle(javax.swing.JLabel lbl_cancle) {
		this.lbl_cancle = lbl_cancle;
	}

	public javax.swing.JLabel getLbl_do() {
		return lbl_do;
	}

	public void setLbl_do(javax.swing.JLabel lbl_do) {
		this.lbl_do = lbl_do;
	}

	public javax.swing.JLabel getLbl_info() {
		return lbl_info;
	}

	public void setLbl_info(javax.swing.JLabel lbl_info) {
		this.lbl_info = lbl_info;
	}

	public javax.swing.JLabel getLbl_newpassword() {
		return lbl_newpassword;
	}

	public void setLbl_newpassword(javax.swing.JLabel lbl_newpassword) {
		this.lbl_newpassword = lbl_newpassword;
	}

	public javax.swing.JLabel getLbl_newvid() {
		return lbl_newname;
	}

	public void setLbl_newvid(javax.swing.JLabel lbl_newvid) {
		this.lbl_newname = lbl_newvid;
	}

	public javax.swing.JLabel getLbl_password() {
		return lbl_password;
	}

	public void setLbl_password(javax.swing.JLabel lbl_password) {
		this.lbl_password = lbl_password;
	}

	public javax.swing.JTextField getTxt_newid() {
		return txt_newname;
	}

	public void setTxt_newid(javax.swing.JTextField txt_newid) {
		this.txt_newname = txt_newid;
	}

	public javax.swing.JPasswordField getTxt_newpassword() {
		return txt_newpassword;
	}

	public void setTxt_newpassword(javax.swing.JPasswordField txt_newpassword) {
		this.txt_newpassword = txt_newpassword;
	}


	public javax.swing.JPasswordField getTxt_password() {
		return txt_password;
	}

	public void setTxt_password(javax.swing.JPasswordField txt_password) {
		this.txt_password = txt_password;
	}

	public javax.swing.JTextField getTxt_vid() {
		return txt_name;
	}

	public void setTxt_vid(javax.swing.JTextField txt_vid) {
		this.txt_name = txt_vid;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
txt_name = new javax.swing.JTextField();
txt_name.setBounds(124, 49, 122, 21);
lbl_password = new javax.swing.JLabel();
lbl_password.setBounds(335, 52, 73, 15);
txt_password = new javax.swing.JPasswordField();
txt_password.setBounds(400, 49, 139, 21);
jSeparator1 = new javax.swing.JSeparator();
jSeparator1.setBounds(10, 148, 871, 10);
jbt_ok = new javax.swing.JButton();
jbt_ok.addActionListener(new ActionListener() {
	public void actionPerformed(ActionEvent e) {
		String name = txt_name.getText();
		String password= txt_password.getText();
		DefaultListModel model = new DefaultListModel();

		Customer ct = CustomerService.query(name);
		
		if (ct == null) {
			// JOptionPane.showMessageDialog(null, "");
			model.addElement("客户不存在！！！");
		} else {
			if(password.equals(ct.getPassword())){
				model.addElement("姓名:" + ct.getName());
				model.addElement("性别:" + ct.getSex());
				model.addElement("电话:" + ct.getPhone());
//				model.addElement("状态："+ct.getCustomerState().getName());
			}
			
		}

		jList1.setModel(model);
		
		CustomerService.update(ct);
	}
});
jbt_ok.setBounds(400, 107, 69, 23);
jbt_cancle1 = new javax.swing.JButton();
jbt_cancle1.addActionListener(new ActionListener() {
	public void actionPerformed(ActionEvent e) {
		txt_name.setText("");
		txt_password.setText("");
		
	}
});
jbt_cancle1.setBounds(479, 107, 69, 23);
lbl_do = new javax.swing.JLabel();
lbl_do.setBounds(20, 168, 93, 15);
lbl_cancle = new javax.swing.JLabel();
lbl_cancle.setBounds(23, 10, 90, 15);
lbl_newname = new javax.swing.JLabel();
lbl_newname.setBounds(61, 193, 96, 15);
txt_newname = new javax.swing.JTextField();
txt_newname.setBounds(137, 190, 134, 21);
lbl_newpassword = new javax.swing.JLabel();
lbl_newpassword.setBounds(61, 284, 72, 15);
txt_newpassword = new javax.swing.JPasswordField();
txt_newpassword.setBounds(137, 281, 134, 21);
jbt_save = new javax.swing.JButton();
jbt_save.addActionListener(new ActionListener() {
	public void actionPerformed(ActionEvent e) {
		String name = txt_newname.getText();
		String password=txt_oldpass.getText();

		
		Customer ct = CustomerService.query(name);
		if(password.equals(ct.getPassword())){
			ct.setPassword(txt_newpassword.getText());
//			CustomerState cts = new CustomerState();
//			cts.setName("激活");
//			ct.setCustomerState(cts);
			
			CustomerService.update(ct);
			JOptionPane.showMessageDialog(null, ct.getName()+"客户已经成功补办！");
		
		}
	}
});
jbt_save.setBounds(215, 388, 69, 23);
jbt_cancle2 = new javax.swing.JButton();
jbt_cancle2.addActionListener(new ActionListener() {
	public void actionPerformed(ActionEvent e) {
		txt_newname.setText("");
		txt_oldpass.setText("");
		txt_newpassword.setText("");
		
	}
});
jbt_cancle2.setBounds(323, 388, 69, 23);
lbl_info = new javax.swing.JLabel();
lbl_info.setBounds(419, 168, 73, 15);
jScrollPane1 = new javax.swing.JScrollPane();
jScrollPane1.setBounds(419, 203, 194, 198);

lbl_password.setText("\u4f1a\u5458\u5bc6\u7801\uff1a");

jbt_ok.setText("\u6ce8  \u9500");

jbt_cancle1.setText("\u53d6  \u6d88");

lbl_do.setText("\u4f1a\u5458\u5361\u8865\u529e\uff1a");

lbl_cancle.setText("\u4f1a\u5458\u5361\u6ce8\u9500\uff1a");

lbl_newname.setText("\u4F1A\u5458\u59D3\u540D\uFF1A");

lbl_newpassword.setText("\u5bc6    \u7801\uff1a");

jbt_save.setText("\u8865  \u529e");

jbt_cancle2.setText("\u53d6  \u6d88");

lbl_info.setText("\u4f1a\u5458\u4fe1\u606f\uff1a");
setLayout(null);
add(txt_name);
add(lbl_password);
add(txt_password);
add(jbt_ok);
add(jbt_cancle1);
add(jSeparator1);
add(lbl_do);
add(lbl_info);
add(lbl_cancle);
add(lbl_newname);
add(lbl_newpassword);
add(txt_newpassword);
add(txt_newname);
add(jbt_save);
add(jbt_cancle2);
add(jScrollPane1);
jList1 = new javax.swing.JList();
jScrollPane1.setViewportView(jList1);
lbl_name = new JLabel("\u5BA2\u6237\u59D3\u540D\uFF1A");
lbl_name.setBounds(61, 52, 83, 15);
add(lbl_name);
lbl_oldpass = new JLabel("\u539F \u5BC6 \u7801\uFF1A");
lbl_oldpass.setBounds(61, 240, 83, 15);
add(lbl_oldpass);
txt_oldpass = new JTextField();
txt_oldpass.setBounds(137, 237, 134, 21);
add(txt_oldpass);
txt_oldpass.setColumns(10);
}// </editor-fold>

	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JList jList1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JButton jbt_cancle1;
	private javax.swing.JButton jbt_cancle2;
	private javax.swing.JButton jbt_ok;
	private javax.swing.JButton jbt_save;
	private javax.swing.JLabel lbl_cancle;
	private javax.swing.JLabel lbl_do;
	private javax.swing.JLabel lbl_info;
	private javax.swing.JLabel lbl_newpassword;
	private javax.swing.JLabel lbl_newname;
	private javax.swing.JLabel lbl_password;
	private javax.swing.JTextField txt_newname;
	private javax.swing.JPasswordField txt_newpassword;
	private javax.swing.JPasswordField txt_password;
	private javax.swing.JTextField txt_name;
	private JLabel lbl_name;
	private JLabel lbl_oldpass;
	private JTextField txt_oldpass;
}