/*
 * V_information.java
 *
 * Created on __DATE__, __TIME__
 */

package com.CCL.view.huiyuan.son;

/**
 *
 * @author  __USER__
 */
public class V_information extends javax.swing.JPanel {

	/** Creates new form V_information */
	public V_information() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		lbl_info = new javax.swing.JLabel();

		lbl_info.setText("\u4f1a\u5458\u4e2a\u4eba\u4fe1\u606f\uff1a");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(28, 28, 28)
						.addComponent(lbl_info)
						.addContainerGap(567, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(22, 22, 22)
						.addComponent(lbl_info)
						.addContainerGap(403, Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel lbl_info;
	// End of variables declaration//GEN-END:variables

}