/*
 * V_information.java
 *
 * Created on __DATE__, __TIME__
 */

package com.CCL.view.huiyuan.son;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.List;

import javax.swing.AbstractListModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ListCellRenderer;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;

import com.CCL.beans.Customer;
import com.CCL.beans.OpeUser;
import com.CCL.view.huiyuan.model.CustomerListModel;
import com.CCL.view.huiyuan.rend.CustomerListRenderer;
import com.CCL.view.huiyuan.service.CustomerService;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.ListSelectionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author  __USER__
 */
public class V_information extends javax.swing.JPanel {

	/** Creates new form V_information */
	public V_information() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		lbl_info = new javax.swing.JLabel();
		lbl_info.setBounds(28, 22, 123, 15);

		lbl_info.setText("\u5BA2\u6237\u4E2A\u4EBA\u4FE1\u606F\u67E5\u8BE2\uFF1A");
		
		JScrollPane scrollPane = new JScrollPane();
		scrollPane.setBounds(28, 128, 204, 274);
		
		JLabel lblNewLabel = new JLabel("\u67E5\u627E\uFF1A");
		lblNewLabel.setBounds(28, 79, 50, 15);
		
		textSearch = new JTextField();
		textSearch.setBounds(68, 76, 147, 21);
		textSearch.addKeyListener(new KeyAdapter() {
			@Override
			public void keyReleased(KeyEvent e) {
				updateUserlist();
			}
		});
		
		
		textSearch.setColumns(10);
		
		lbl_name = new JLabel("\u59D3\u540D\uFF1A");
		lbl_name.setBounds(293, 95, 45, 15);
		
		lbl_name1 = new JLabel("");
		lbl_name1.setBounds(344, 93, 63, 17);
		lbl_name1.setForeground(Color.RED);
		
		lbl_sex = new JLabel("\u6027\u522B:");
		lbl_sex.setBounds(443, 95, 38, 15);
		
		lbl_sex1 = new JLabel("");
		lbl_sex1.setBounds(487, 95, 48, 15);
		lbl_sex1.setForeground(Color.RED);
		
		lbl_tel = new JLabel("\u7535\u8BDD\uFF1A");
		lbl_tel.setBounds(293, 156, 42, 15);
		
		lbl_tel1 = new JLabel("");
		lbl_tel1.setBounds(349, 153, 78, 18);
		lbl_tel1.setForeground(Color.RED);
		
		lbl_email = new JLabel("EMAIL\uFF1A");
		lbl_email.setBounds(443, 156, 63, 15);
		
		lbl_email1 = new JLabel("");
		lbl_email1.setBounds(495, 151, 144, 20);
		lbl_email1.setForeground(Color.RED);
		
		lbl_type = new JLabel("\u7C7B\u578B\uFF1A");
		lbl_type.setBounds(293, 225, 46, 15);
		
		lbl_type1 = new JLabel("");
		lbl_type1.setBounds(349, 222, 86, 18);
		lbl_type1.setForeground(Color.RED);
		
		lbl_state = new JLabel("\u72B6\u6001\uFF1A");
		lbl_state.setBounds(445, 225, 44, 15);
		
		lbl_state1 = new JLabel("");
		lbl_state1.setBounds(499, 225, 87, 15);
		lbl_state1.setForeground(Color.RED);
		
		lbl_address = new JLabel("\u5730\u5740\uFF1A");
		lbl_address.setBounds(293, 396, 40, 15);
		
		lbl_address1 = new JLabel("");
		lbl_address1.setBounds(339, 391, 144, 20);
		lbl_address1.setForeground(Color.RED);
		
		lbl_date = new JLabel("\u51FA\u751F\u65E5\u671F\uFF1A");
		lbl_date.setBounds(293, 345, 78, 15);
		
		lbl_date1 = new JLabel("");
		lbl_date1.setBounds(359, 339, 162, 21);
		lbl_date1.setForeground(Color.RED);
		
		lbl_intal = new JLabel("\u79EF\u5206\uFF1A");
		lbl_intal.setBounds(293, 297, 50, 15);
		
		lbl_intal1 = new JLabel("");
		lbl_intal1.setBounds(349, 291, 79, 17);
		lbl_intal1.setForeground(Color.RED);
		
		lbl_money = new JLabel("\u4F59\u989D\uFF1A");
		lbl_money.setBounds(446, 297, 40, 15);
		
		lbl_money1 = new JLabel("");
		lbl_money1.setBounds(488, 291, 68, 21);
		lbl_money1.setForeground(Color.RED);
		
		userlist = new JList<Customer>();
		userlist.addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent e) {
				
				Customer ct = userlist.getSelectedValue();
				lbl_address1.setText(ct.getAddress());
				lbl_date1.setText(ct.getBirthday()+"");
				lbl_email1.setText(ct.getEmail());
				lbl_intal1.setText(ct.getIntegral()+"");
				lbl_type1.setText(ct.getCustomerType().getName());
				lbl_tel1.setText(ct.getPhone());
				lbl_money1.setText(ct.getMoney().toString());
				lbl_name1.setText(ct.getName());
				lbl_state1.setText(ct.getCustomerState()+"");
				lbl_sex1.setText(ct.getSex());
				
			}
		});
		setLayout(null);
		
		userlist.setCellRenderer(new CustomerListRenderer());
		
		scrollPane.setViewportView(userlist);
		add(scrollPane);
		add(lbl_name);
		add(lbl_name1);
		add(lbl_sex);
		add(lbl_sex1);
		add(lbl_email);
		add(lbl_email1);
		add(lbl_tel);
		add(lbl_type);
		add(lbl_tel1);
		add(lbl_type1);
		add(lbl_state);
		add(lbl_state1);
		add(lbl_address);
		add(lbl_address1);
		add(lbl_date);
		add(lbl_date1);
		add(lbl_intal);
		add(lbl_intal1);
		add(lbl_money);
		add(lbl_money1);
		add(lblNewLabel);
		add(textSearch);
		add(lbl_info);
	}// </editor-fold>
	//GEN-END:initComponents

	protected void updateUserlist() {
		// TODO Auto-generated method stub
		String text = textSearch.getText();
		
		List<Customer> query = CustomerService.queryUserByKeyWord(text);
		
		userlist.setModel(new CustomerListModel(query));
		
		
	}
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel lbl_info;
	private JTextField textSearch;
	private JList<Customer> userlist;
	private JLabel lbl_name;
	private JLabel lbl_name1;
	private JLabel lbl_sex;
	private JLabel lbl_sex1;
	private JLabel lbl_tel;
	private JLabel lbl_tel1;
	private JLabel lbl_email;
	private JLabel lbl_email1;
	private JLabel lbl_type;
	private JLabel lbl_type1;
	private JLabel lbl_state;
	private JLabel lbl_state1;
	private JLabel lbl_address;
	private JLabel lbl_address1;
	private JLabel lbl_date;
	private JLabel lbl_date1;
	private JLabel lbl_intal;
	private JLabel lbl_intal1;
	private JLabel lbl_money;
	private JLabel lbl_money1;
	
	
	
	
}