/*
 * V_records.java
 *
 * Created on __DATE__, __TIME__
 */

package com.CCL.view.huiyuan.son;

/**
 *
 * @author  __USER__
 */
public class V_records extends javax.swing.JPanel {

	/** Creates new form V_records */
	public V_records() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		lbl_record = new javax.swing.JLabel();

		lbl_record.setText("\u4f1a\u5458\u6d88\u8d39\u8bb0\u5f55");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(23, 23, 23)
						.addComponent(lbl_record)
						.addContainerGap(584, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap()
						.addComponent(lbl_record)
						.addContainerGap(414, Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel lbl_record;
	// End of variables declaration//GEN-END:variables

}