/*
 * panel_UserAuthorzatiom.java
 *
 * Created on __DATE__, __TIME__
 */

package com.CCL.panel.mlf;

import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;

import com.CCL.Dao.OpeUserDao;
import com.CCL.Dao.OpeperDao;
import com.CCL.Dao.impl.OpeUserDaoImpl;
import com.CCL.Dao.impl.OpeperDaoImpl;
import com.CCL.beans.OpeUser;
import com.CCL.beans.Opeper;
import com.CCL.service.mlf.opeper_service;
import com.CCL.util.mlf.PublicDate;

/**
 *
 * @author  __USER__
 */
public class panel_UserAuthorzatiom extends javax.swing.JPanel {

	private OpeUser Ouser;
	private opeper_service opservice;
	private OpeUserDao opusedao;
	private OpeperDao opedao;
	private Opeper op;
    private   opeper_service opeservice;
    private static String major = null;
    
	public panel_UserAuthorzatiom() {
		op = new Opeper();
		opedao = new OpeperDaoImpl();
		Ouser = PublicDate.getOuser();
		opservice = new opeper_service();
		opusedao = new OpeUserDaoImpl();
		 opeservice=new opeper_service();
		initComponents();

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

jScrollPane1 = new javax.swing.JScrollPane();
jList_major = new javax.swing.JList();
jScrollPane2 = new javax.swing.JScrollPane();
jList_small = new javax.swing.JList();
lbl_majorfuction = new javax.swing.JLabel();
lbl_subfunction = new javax.swing.JLabel();
lbl_id = new javax.swing.JLabel();
lbl_username = new javax.swing.JLabel();
txt_name = new java.awt.TextField();
btn_grantright = new java.awt.Button();
btn_all_grantright = new java.awt.Button();
btn_remove = new java.awt.Button();
btn_all_remove = new java.awt.Button();
btn_return = new java.awt.Button();
jLabel1 = new javax.swing.JLabel();
jScrollPane3 = new javax.swing.JScrollPane();
jList_current = new javax.swing.JList();
jLabel2 = new javax.swing.JLabel();
jComboBox1 = new javax.swing.JComboBox();

setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

jList_major.setFont(new java.awt.Font("Microsoft YaHei UI", 3, 14));
jList_major.setModel(new javax.swing.AbstractListModel() {
String[] strings = { "前台收银管理", "会员卡管理", "系统管理", "其它" };
public int getSize() { return strings.length; }
public Object getElementAt(int i) { return strings[i]; }
});
jScrollPane1.setViewportView(jList_major);

add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, 470));

List<OpeUser> user=opusedao.queryAll();
for (OpeUser u : user) {

	jComboBox1.addItem(u);// 添加管理员
};
Ouser=(OpeUser)jComboBox1.getSelectedItem();
op=opedao.get(Ouser.getId());
txt_name.setText(Ouser.getUserName());
jList_current.setListData(opeservice.readQuanXian(op,1));
panel_UserAuthorzatiom.this.repaint();
///////////////////
jList_major.setSelectedIndex(0);
jList_major.addMouseListener(new MouseAdapter() {
	  
	public void mouseClicked(MouseEvent e) {
		 JListmajor_mouseAction(e);
		
		}
	
});




//jList_small.setModel([]);
jScrollPane2.setViewportView(jList_small);

add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, 470));

lbl_majorfuction.setText("\u4e3b\u8981\u529f\u80fd");
add(lbl_majorfuction, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

lbl_subfunction.setText("\u76f8\u5173\u5b50\u529f\u80fd");
add(lbl_subfunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, 20));

lbl_id.setText("ID:");
add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 273, -1, -1));

lbl_username.setText("\u7528\u6237\u540d:");
add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, -1, -1));

txt_name.setEditable(false);
add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 180, 90, -1));

btn_grantright.setLabel("\u6388\u6743");
add(btn_grantright, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 65, -1));

btn_grantright.addMouseListener(new MouseAdapter() {
	@Override
	public void mouseClicked(MouseEvent e) {
		if(e.getClickCount()==2)			
		{  
              btngrantright_MouseAction(e);
		}
	}
});

btn_all_grantright.setLabel("\u5168\u90e8\u6388\u6743");
add(btn_all_grantright, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

btn_all_grantright.addMouseListener(new MouseAdapter() {
	@Override
	public void mouseClicked(MouseEvent e) {
		btnallgrantright_MouseAction(e);
	}
});


btn_remove.setLabel("\u64a4\u9500");

add(btn_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 65, -1));

btn_remove.addMouseListener(new MouseAdapter() {
	@Override
	public void mouseClicked(MouseEvent e) {
		btnremove_MouseAction(e);
	}
});

btn_all_remove.setLabel("\u5168\u90e8\u64a4\u9500");
add(btn_all_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));

btn_all_remove.addMouseListener(new MouseAdapter() {

	public void mouseClicked(MouseEvent e) {
		btnallremove_MouseAction(e);
	}
});

btn_return.setLabel("\u9000\u51fa");
add(btn_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 65, -1));

jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 3, 24));
jLabel1.setForeground(new java.awt.Color(255, 0, 0));
jLabel1.setText("\u7528\u6237\u6388\u6743\u7ba1\u7406");
add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

//jList_current.setModel([]);
jScrollPane3.setViewportView(jList_current);

add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 180, 460));




jLabel2.setText("\u5f53\u524d\u4f7f\u7528\u529f\u80fd");
add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, -1));



add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 270, 90, -1));

jComboBox1.addItemListener(new ItemListener() {
	
	@Override
	public void itemStateChanged(ItemEvent e) {
		Ouser=(OpeUser)jComboBox1.getSelectedItem();
		op=opedao.get(Ouser.getId());
		txt_name.setText(Ouser.getUserName());
		jList_current.setListData(opeservice.readQuanXian(op,1));
		////////////////////////////////////
		jList_small.setListData(opservice.readQuanxian_vctor(op,(jList_major.getSelectedValue()).toString(),0));
				jList_small.repaint();
			
		panel_UserAuthorzatiom.this.repaint();
	}
});

	}// </editor-fold>

	protected void btnallremove_MouseAction(MouseEvent e) {
		int i=jList_current.getLastVisibleIndex();
		if(i<0)
		{
			JOptionPane.showMessageDialog(null, "此用户已无任何权限");
		}
		else{
			Ouser=(OpeUser)jComboBox1.getSelectedItem();
			op=opedao.get(Ouser.getId());
			for(int j=0;j<=i;j++)
			{    			
				String name=(String)jList_current.getModel().getElementAt(0);
				opeservice.shouQuan(op, name, 0);
				jList_current.setListData(opeservice.readQuanXian(op,1));
				JListmajor_mouseAction(e);
				jList_small.repaint();
			}
		}
		
	}

	protected void btnremove_MouseAction(MouseEvent e) {
		int i=jList_current.getSelectedIndex();
		if(i<0)
		{
			JOptionPane.showMessageDialog(null, "请选择要撤销的权限");
		}else
		{
			
		String  name=(String)jList_current.getSelectedValue();
		Ouser=(OpeUser)jComboBox1.getSelectedItem();
		op=opedao.get(Ouser.getId());
		opeservice.shouQuan(op, name, 0);
		jList_current.setListData(opeservice.readQuanXian(op,1));
//		jList_small.setListData(opeservice.readQuanxian_vctor(op, major, 0));
		JListmajor_mouseAction(e);
		jList_small.repaint();
		}
	}

	protected void btnallgrantright_MouseAction(MouseEvent e) {
		int i=jList_small.getLastVisibleIndex();//jList_small.getModel().getSize();
		if(i<0)
		{
			JOptionPane.showMessageDialog(null, "此主功能模块的说有权限都已拥有");
		}
		else{
			for(int j=0;j<=i;j++)
			{    
				
				Ouser=(OpeUser)jComboBox1.getSelectedItem();
				op=opedao.get(Ouser.getId());
				String name=(String)jList_small.getModel().getElementAt(0);
				opeservice.shouQuan(op, name, 1);
				jList_current.setListData(opeservice.readQuanXian(op,1));
				jList_small.setListData(opeservice.readQuanxian_vctor(op, major, 0));
			}
			
			
		}
		
	}

	protected void JListmajor_mouseAction(MouseEvent e) {
			
	     jList_small.removeAll();
		      
		   DefaultListModel  listmodel=new DefaultListModel();
			major=(String)jList_major.getSelectedValue();
			if(major.equals("前台收银管理"))
			{
				jList_small.setListData(opservice.readQuanxian_vctor(op,"前台收银管理",0));
				jList_small.repaint();
////				opeservice.readQuanXian(opeper, list, i)             
//				listmodel.addElement("换车功能");
//				listmodel.addElement("积分兑换");
//				listmodel.addElement("积分打印功能");								
			}
			if(major.equals("会员卡管理"))
			{
				jList_small.setListData(opservice.readQuanxian_vctor(op,"会员卡管理",0));
				jList_small.repaint();
//				listmodel.addElement("会员卡充值");
//				listmodel.addElement("余额查询");	
//				listmodel.addElement("信息修改");
//				listmodel.addElement("消费记录查询");
//				listmodel.addElement("会员卡补办");
//				listmodel.addElement("会员卡升级");
			}
			if(major.equals("系统管理"))
			{
				jList_small.setListData(opservice.readQuanxian_vctor(op,"系统管理",0));
				jList_small.repaint();
//				listmodel.addElement("收费设置");
//				listmodel.addElement("折扣设置");	
//				listmodel.addElement("车辆管理");
				
			}
			if(major.equals("其它"))
			{
				jList_small.setListData(opservice.readQuanxian_vctor(op,"其它",0));
				jList_small.repaint();
//				listmodel.addElement("数据备份");
				
//				listmodel.addElement("短信提醒");	

				
			}
//			jList_small.setModel(listmodel);
	
		
	}

	protected void btngrantright_MouseAction(MouseEvent e) {
		String name=(String)jList_small.getSelectedValue();
		if(jList_small.getSelectedIndex()<0)
		{
			JOptionPane.showMessageDialog(null, "请选择相应子功能进行授权");
		}
		else
		{
			Ouser=(OpeUser)jComboBox1.getSelectedItem();
			op=opedao.get(Ouser.getId());
			opeservice.shouQuan(op, name, 1);
			jList_current.setListData(opeservice.readQuanXian(op,1));
			jList_small.setListData(opeservice.readQuanxian_vctor(op, major, 0));
		}
		
		
		
	}

	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private java.awt.Button btn_all_grantright;
	private java.awt.Button btn_all_remove;
	private java.awt.Button btn_grantright;
	private java.awt.Button btn_remove;
	private java.awt.Button btn_return;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JList jList_current;
	private javax.swing.JList jList_major;
	private javax.swing.JList jList_small;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JLabel lbl_id;
	private javax.swing.JLabel lbl_majorfuction;
	private javax.swing.JLabel lbl_subfunction;
	private javax.swing.JLabel lbl_username;
	private java.awt.TextField txt_name;
	// End of variables declaration//GEN-END:variables

}